# echo-shell v2

## Description

Even after downgrading the shell, we got attacked by unamed man again. Could you figured it out?

*Note: The log was captured on client side*

## Release

- server.py
- shell.pcap

## Flag

`MDT4.0{why_this_th1ng_st1ll_ech01ng_183dba4}`
